# Generated by Django 2.0.2 on 2019-03-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nattracker', '0002_auto_20190301_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='situation_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='thought',
            name='thought_text',
            field=models.CharField(max_length=256000),
        ),
    ]
